// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/27/2026, 4:07:47 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/applet/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/plugins/**/*.{js,ts,mjs}","/app/applet/composables/**/*.{js,ts,mjs}","/app/applet/utils/**/*.{js,ts,mjs}","/app/applet/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/applet/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/applet/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;